### ISSUE TITLE
Permission to use in amogOS

### ISSUE THREAD

**Issue by NoozAbooz** [sueperb/tasty-grubs#1]
Hello! I'm a developer on the [amogOS](https://github.com/jostroOS/amogOS) project. I recently stumbled onto this, and I'd like to ask for permission to include this in the OS? I can put credits to the github repo in the readme.

**Comment by divory100** [comment]
Sure no problem! If you credited this repo that would be great as well :)

**Comment by NoozAbooz** [comment]
Thanks so much!
